import {NextRequest,NextResponse} from "next/server";
const groups:Record<string,string[]>={"React":["react","next.js"],"TypeScript":["typescript"],"Angular":["angular"],"Java":["java"],"Spring Boot":["spring boot","springboot"],"Microservices":["microservice"],"REST APIs":["rest api","restful"],"MySQL":["mysql"],"Oracle SQL":["oracle sql","oracle database","pl/sql"],"AWS":["aws","amazon web services"],"Azure":["azure"],"Docker":["docker"],"Kubernetes":["kubernetes","k8s"],"CI/CD":["ci/cd","continuous integration"],"Generative AI":["generative ai","genai","openai","llm"],"Leadership":["lead team","team lead","mentoring","leadership"]};
const has=(text:string,terms:string[])=>terms.some(term=>text.includes(term));
function localAnalysis(role:string,company:string,description:string,profile:string){
 const job=description.toLowerCase(),candidate=profile.toLowerCase(),required=Object.entries(groups).filter(([,t])=>has(job,t));
 const matched=required.filter(([,t])=>has(candidate,t)).map(([n])=>n),missing=required.filter(([,t])=>!has(candidate,t)).map(([n])=>n);
 const coverage=required.length?matched.length/required.length:.62,years=Number(candidate.match(/(\d+(?:\.\d+)?)\s*years?/)?.[1]||0),requested=Number(job.match(/(\d+)\+?\s*(?:to\s*\d+\s*)?years?/)?.[1]||0),experienceFit=!requested||years>=requested;
 const score=Math.max(45,Math.min(96,Math.round(50+coverage*40+(experienceFit?6:-7)))),matches=matched.length?matched.slice(0,7):["Relevant full-stack experience"],gaps=missing.length?missing.slice(0,5):["Quantified impact examples"],matchText=matches.slice(0,3).join(", ");
 return {score,matchedSkills:matches,missingSkills:gaps,summary:`${experienceFit?"Your experience level aligns with this role.":"The role may ask for more experience than shown in your summary."} Your strongest evidence is in ${matchText}. Address ${gaps[0]} directly, without claiming experience you do not have.`,resumeSuggestions:[`Move ${matchText} into the top third of your resume and mirror the job’s wording where accurate.`,"Add one measurable outcome to your most relevant project, such as latency reduced, users served, delivery time saved, or team size led.",`Address “${gaps[0]}” through transferable experience or a short learning project; do not list it as mastered unless true.`],recruiterMessage:`Hi, I’m interested in the ${role} opportunity at ${company}. I bring ${years||"several"} years of full-stack experience, with hands-on work in ${matchText}. I’ve delivered production applications and AI-enabled workflows, and the role looks closely aligned with my background. I’d be glad to share relevant project details.`,coverLetter:`Dear Hiring Team,\n\nI am applying for the ${role} position at ${company}. With ${years||"several"} years of full-stack development experience, I offer practical expertise in ${matchText}, along with ownership of customer-facing software from implementation through delivery.\n\nIn my recent work, I have built web applications, backend services, and AI-enabled workflows. I focus on reliable delivery, clear APIs, maintainable code, and collaboration. While ${gaps[0]} is an area I would discuss transparently, my adjacent experience gives me a solid base to learn and contribute quickly.\n\nI would welcome the opportunity to discuss how my experience can support ${company}.\n\nRegards,\nTanmay Dagaonkar`};
}
export async function POST(request:NextRequest){try{const {role,company,jobDescription,profile}=await request.json();if(![role,company,jobDescription,profile].every(v=>typeof v==="string"&&v.trim()))return NextResponse.json({error:"Please complete all four fields."},{status:400});if(jobDescription.length<80||profile.length<40)return NextResponse.json({error:"Add a fuller job description and experience summary."},{status:400});return NextResponse.json(localAnalysis(role.trim(),company.trim(),jobDescription,profile))}catch{return NextResponse.json({error:"The request could not be processed."},{status:500})}}
